#!/bin/bash
set -e
set -u

# Delete the config files
#rm ${KARAF_BASE}etc/org.postgresql.ds.cfg
#rm ${KARAF_BASE}etc/aries.jpa.persistence.paasplus.nosql.cfg
#rm ${KARAF_BASE}etc/org.mongodb.connection.cfg

if [ -n "${OPENSHIFT_POSTGRESQL_DB_USERNAME+x}" ]; then
  # Replace postgres config file with the template
  cp -f ${OPENSHIFT_KARAF_DIR}usr/versions/shared/etc/org.postgresql.ds.cfg ${KARAF_BASE}/etc/org.postgresql.ds.cfg
  # Replace postgres variables
  echo "setting postgresql connection credentials"
  sed -i "s/\$HOST/$OPENSHIFT_POSTGRESQL_DB_HOST/g"         ${KARAF_BASE}/etc/org.postgresql.ds.cfg
  sed -i "s/\$PORT/$OPENSHIFT_POSTGRESQL_DB_PORT/g"         ${KARAF_BASE}/etc/org.postgresql.ds.cfg
  sed -i "s/\$DATABASE/$OPENSHIFT_APP_NAME/g"               ${KARAF_BASE}/etc/org.postgresql.ds.cfg
  sed -i "s/\$USER/$OPENSHIFT_POSTGRESQL_DB_USERNAME/g"     ${KARAF_BASE}/etc/org.postgresql.ds.cfg
  sed -i "s/\$PASSWORD/$OPENSHIFT_POSTGRESQL_DB_PASSWORD/g" ${KARAF_BASE}/etc/org.postgresql.ds.cfg
fi

if [ -n "${OPENSHIFT_MONGODB_DB_USERNAME+x}" ]; then
  # Replace mongo config files with the templates
  cp -f ${OPENSHIFT_KARAF_DIR}usr/versions/shared/etc/aries.jpa.persistence.paasplus.nosql.cfg ${KARAF_BASE}/etc/aries.jpa.persistence.paasplus.nosql.cfg
  cp -f ${OPENSHIFT_KARAF_DIR}usr/versions/shared/etc/org.mongodb.connection.cfg ${KARAF_BASE}/etc/org.mongodb.connection.cfg
  # Replace mongo variables
  echo "setting mongodb connection credentials"
  sed -i "s/\$HOST/$OPENSHIFT_MONGODB_DB_HOST/g"         ${KARAF_BASE}/etc/org.mongodb.connection.cfg
  sed -i "s/\$PORT/$OPENSHIFT_MONGODB_DB_PORT/g"         ${KARAF_BASE}/etc/org.mongodb.connection.cfg
  sed -i "s/\$DB/$OPENSHIFT_APP_NAME/g"                  ${KARAF_BASE}/etc/org.mongodb.connection.cfg
  sed -i "s/\$USER/$OPENSHIFT_MONGODB_DB_USERNAME/g"     ${KARAF_BASE}/etc/org.mongodb.connection.cfg
  sed -i "s/\$PASSWORD/$OPENSHIFT_MONGODB_DB_PASSWORD/g" ${KARAF_BASE}/etc/org.mongodb.connection.cfg
fi